version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    image: fastapi_websocket:${FASTAPI_WEBSOCKET_VERSION:-latest}
    restart: always
    env_file:
    - .env
    environment:
      FASTAPI_WEBSOCKET_HOST: 0.0.0.0
